[package]
name = "object"
version = "0.1.0"
authors = ["decaruju <julien.decarufel@gmail.com>"]
edition = "2018"

[lib]
name = "object"
path = "src/lib.rs"

[dependencies]
parser = { path = "../parser" }
libloading = "0.6.1"