[package]
name = "lim-rust-std"
version = "0.1.0"
authors = ["decaruju <julien.decarufel@gmail.com>"]
edition = "2018"


[lib]
name = "std"
crate_type = ["dylib"]

[dependencies]
object = { path = "../object" }